export const podiumData = [

  {
    name: "Best 1st Year Hack",
    amt: "Cash Prize-TBA",
    webp: "prizes/webp/2nd.webp",
    img: "prizes/2nd.png",
    id: "g",
    cStyle: {
      paddingLeft: "5%",
      paddingRight: "5%",
      paddingTop: "7%",
      width: "10%",
      marginTop: "4%",
      top: "-1.5rem",
      position: "relative",
      marginLeft: "2%",
      
    },
    desc: [
      "Rs.500 Coupon From GFG",
      "Lifetime upgrade of Taskade",
      "Unlimited mock interviews from Interview Buddy",
      "Swags and Stickers",
    ],
  },
  {
    name: "Best Overall Hack",
    amt: "Cash Prize-TBA",
    webp: "prizes/webp/1st.webp",
    img: "prizes/1st.png",
    id: "w",
    cStyle: {
      paddingLeft: "5%",
      paddingRight: "5%",
      paddingTop: "7%",
      width: "10%",
      marginTop:"4%",
      top: "-1.5rem",
      position: "relative",
      marginLeft: "2%",
    },
    desc: [
      "Rs.1200 Coupon From GFG",
      "Wolfram Award letter",
      "Lifetime upgrade of Taskade",
      "Unlimited mock interviews from Interview Buddy",
      "Swags and Stickers",
    ],
  },
  {
    name: "Individual Track Prize",
    amt: "Cash Prize-TBA",
    webp: "prizes/webp/3rd.webp",
    img: "prizes/3rd.png",
    id: "r",
    cStyle: {
      paddingLeft: "5%",
      paddingRight: "5%",
      paddingTop: "12%",
      top: "-1.5rem",
      position: "relative",
      marginLeft: "2%",
    },
    desc: [
      "Rs.800 Coupon From GFG",
      "Wolfram Award letter",
      "Lifetime upgrade of Taskade",
      "Unlimited mock interviews from Interview Buddy",
      "Swags and Stickers",
    ],
  },
];
export const prizesData = [
  {
    name: "Defence",
    amt: "Cash Prize",
    webp: "prizes/webp/climate.webp",
    img: "prizes/climate.png",
    desc: [
      "Wolfram Award letter",
      "Coding Minutes Course for each Team Member",
      "Swags and Stickers",
    ],
  },
  {
    name: "Mental Health",
    amt: "Cash Prize",
    webp: "prizes/webp/pandemic.webp",
    img: "prizes/pandemic.png",
    desc: [
      "Wolfram Award letter",
      "Coding Minutes Course for each Team Member",
      "Swags and Stickers",
    ],
  },
  {
    name: "LGBTQ+",
    amt: "Cash Prize",
    webp: "prizes/webp/cyber.webp",
    img: "prizes/cyber.png",
    desc: [
      "Wolfram Award letter",
      "Coding Minutes Course for each Team Member",
      "Swags and Stickers",
    ],
  },
  {
    name: "Period Poverty",
    amt: "Cash Prize",
    webp: "prizes/webp/disaster.webp",
    img: "prizes/disaster.png",
    desc: [
      "Wolfram Award letter",
      "Coding Minutes Course for each Team Member",
      "Swags and Stickers",
    ],
  },
];

export const allParticipants = {
  name: "All Participants",
  amt: "Cash Prize",
  webp: "prizes/webp/parti.webp",
  img: "prizes/parti.png",
  desc: [
    "30% discount coupons from YHills",
    "Full access licenses of Interview Cake for Interview prep",
    "Free Student License from JetBrains",
    "Rs.300 Coupons from GFG",
    "Free domains from Cybrancee",
    "5-Year free upgrades from Taskade",
    "Access to Internship platform of Heiphen",
    "90-day extended trial promo code for Balsamiq Cloud",
    "Coupons for top brands from GrabOn",
    "Premium Tier service from Echo3D",
    "Coupon Voucher from Interview Buddy",
    "1 Free Year of 1Password Families",
    "Expansion Pack worth 100$ from Leading Learners",
    "Internship opportunities to participants Lets grow more",
    "50% discount on sessions by Mentro",
    "60 days full featured license from Proto.io",
    "Coupons from Badelog.in",
    "Coupons from Tech Cryptors valid for 1 year",
    "$100 credits by Digital Ocean",
  ],
};
