export const podiumData = [

  {
    name: "Best 1st Year Hack",
    amt: "Cash Prize - INR 6000",
    webp: "prizes/webp/2nd.webp",
    img: "prizes/2nd.png",
    id: "g",
    cStyle: {
      paddingLeft: "5%",
      paddingRight: "5%",
      paddingTop: "7%",
      width: "10%",
      marginTop: "4%",
      top: "-1.5rem",
      position: "relative",
      marginLeft: "2%",
      
    },
    desc: [
      "T-Shirt from Coding Blocks",
      "Swags and Azure pass from Azure",
      "Free Courses by Coding Minutes",
      "Goodies by Devfolio",
      "Stickers and $250 credits by Digital Ocean",
      "Async online mock interviews with unlimited practice from Interview Buddy",
      "375$ Wolfram Award",
    ],
  },
  {
    name: "Best Overall Hack",
    amt: "Cash Prize - INR 15000",
    webp: "prizes/webp/1st.webp",
    img: "prizes/1st.png",
    id: "w",
    cStyle: {
      paddingLeft: "5%",
      paddingRight: "5%",
      paddingTop: "7%",
      width: "10%",
      marginTop:"4%",
      top: "-1.5rem",
      position: "relative",
      marginLeft: "2%",
    },
    desc: [
      "Goodies from Devfolio",
      "T-Shirts, stickers and $250 credits by Digital Ocean",
      "Free 1 year subscription license from Axure",
      "Free Courses by Coding Blocks",
      "Goodies and Free Courses by Coding Minutes",
      "Amazon voucher worth 2500 INR from Flipr",
      "Art of problem solving vouchers worth $25",
      "Swags and Azure pass from Azure",
      "90 days fully featured license by Proto.io",
      "375$ Wolfram Award",
      "Company Lifetime Package from Clerky",
    ],
  },
  {
    name: "Individual Track Prize",
    amt: "Cash Prize - INR 6000",
    webp: "prizes/webp/3rd.webp",
    img: "prizes/3rd.png",
    id: "r",
    cStyle: {
      paddingLeft: "5%",
      paddingRight: "5%",
      paddingTop: "12%",
      top: "-1.5rem",
      position: "relative",
      marginLeft: "2%",
    },
    desc: [
      "T-Shirt from Coding Blocks",
      "Swags and Azure pass from Azure",
      "Goodies and Free Courses by Coding Minutes",
      "Goodies by Devfolio",
      "Stickers and $250 credits by Digital Ocean",
      "375$ Wolfram Award",
    ],
  },
];
export const prizesData = [
  {
    name: "Defence",
    amt: "Cash Prize",
    webp: "prizes/webp/climate.webp",
    img: "prizes/climate.png",
    desc: [
      "Wolfram Award letter",
      "Coding Minutes Course for each Team Member",
      "Swags and Stickers",
    ],
  },
  {
    name: "Mental Health",
    amt: "Cash Prize",
    webp: "prizes/webp/pandemic.webp",
    img: "prizes/pandemic.png",
    desc: [
      "Wolfram Award letter",
      "Coding Minutes Course for each Team Member",
      "Swags and Stickers",
    ],
  },
  {
    name: "LGBTQ+",
    amt: "Cash Prize",
    webp: "prizes/webp/cyber.webp",
    img: "prizes/cyber.png",
    desc: [
      "Wolfram Award letter",
      "Coding Minutes Course for each Team Member",
      "Swags and Stickers",
    ],
  },
  {
    name: "Period Poverty",
    amt: "Cash Prize",
    webp: "prizes/webp/disaster.webp",
    img: "prizes/disaster.png",
    desc: [
      "Wolfram Award letter",
      "Coding Minutes Course for each Team Member",
      "Swags and Stickers",
    ],
  },
];

export const allParticipants = {
  name: "All Participants",
  amt: "Cash Prize",
  webp: "prizes/webp/parti.webp",
  img: "prizes/parti.png",
  desc: [
    "30% discount coupons from YHills",
    "Full access licenses of Interview Cake for Interview prep",
    "Free Student License from JetBrains",
    "Rs.300 Coupons from GFG",
    "Free domains from Cybrancee",
    "5-Year free upgrades from Taskade",
    "Access to Internship platform of Heiphen",
    "90-day extended trial promo code for Balsamiq Cloud",
    "Coupons for top brands from GrabOn",
    "Premium Tier service from Echo3D",
    "Coupon Voucher from Interview Buddy",
    "1 Free Year of 1Password Families",
    "Expansion Pack worth 100$ from Leading Learners",
    "Internship opportunities to participants Lets grow more",
    "50% discount on sessions by Mentro",
    "60 days full featured license from Proto.io",
    "Coupons from Badelog.in",
    "Coupons from Tech Cryptors valid for 1 year",
    "$100 credits by Digital Ocean",
  ],
};
