export const data = [
  {
    tierName: "Power Sponsors",
    data: [
      {
        sponsorName: "YHills",
        webp: "sponsors/silver/webp/yhills.webp",
        src: "sponsors/silver/yhills.png",
        url: "https://yhills.com/",
        id: "silver_0",
      },
      {
        sponsorName: "Koii",
        webp: "sponsors/silver/webp/koii.webp",
        src: "sponsors/silver/koii.png",
        url: "https://koii.network/",
        id: "silver_1",
      },
      {
        sponsorName: "Celo",
        webp: "sponsors/silver/webp/celo.webp",
        src: "sponsors/silver/celo.png",
        url: "https://celo.org/",
        id: "silver_2",
      },
      {
        sponsorName: "Filecoin",
        webp: "sponsors/silver/webp/filecoin.webp",
        src: "sponsors/silver/filecoin.png",
        url: "https://filecoin.io/",
        id: "silver_3",
      },
      {
        sponsorName: "Tezos",
        webp: "sponsors/silver/webp/tezos.webp",
        src: "sponsors/silver/tezos.png",
        url: "https://tezos.com/",
        id: "silver_4",
      },
      {
        sponsorName: "Github",
        webp: "sponsors/silver/webp/github.webp",
        src: "sponsors/silver/github.png",
        url: "https://www.github.com/",
        id: "silver_5",
      },
      {
        sponsorName: "Stickermule",
        webp: "sponsors/silver/webp/stickermule.webp",
        src: "sponsors/silver/stickermule.png",
        url: "http://hackp.ac/mlh-stickermule-hackathons",
        id: "silver_6",
      },
      {
        sponsorName: "Leading learners",
        webp: "sponsors/silver/webp/leadinglearners.webp",
        src: "sponsors/silver/leadinglearners.png",
        url: "https://www.leadlearners.ca/",
        id: "silver_7",
      },
      {
        sponsorName: "Coding Blocks",
        webp: "sponsors/silver/webp/codingblocks.webp",
        src: "sponsors/silver/codingblocks.png",
        url: "https://codingblocks.com/",
        id: "silver_8",
      },
      {
        sponsorName: "Coding Minutes",
        webp: "sponsors/gold/webp/CodingMinutes.webp",
        src: "sponsors/gold/CodingMinutes.png",
        url: "https://www.codingminutes.com/",
        id: "silver_9",
      },
      {
        sponsorName: "Wolfram",
        webp: "sponsors/silver/webp/wolfram-1.webp",
        src: "sponsors/silver/wolfram-1.png",
        url: "https://www.wolfram.com/",
        id: "silver_10",
      },
      {
        sponsorName: "DigitalOcean",
        webp: "sponsors/silver/webp/DigitalOcean.webp",
        src: "sponsors/silver/DigitalOcean.png",
        url: "https://www.digitalocean.com/",
        id: "silver_11",
      },
    ],
    id: "1",
  },
  {
    tierName: "Associate Sponsors",
    data: [
      {
        sponsorName: "Balsamiq",
        webp: "sponsors/gold/webp/balsamiq.webp",
        src: "sponsors/gold/balsamiq.png",
        url: "https://balsamiq.com/",
        id: "gold_0",
      },
      {
        sponsorName: "Coding Minutes",
        webp: "sponsors/gold/webp/CodingMinutes.webp",
        src: "sponsors/gold/CodingMinutes.png",
        url: "https://www.codingminutes.com/",
        id: "gold_1",
      },
      {
        sponsorName: "1Password",
        webp: "sponsors/gold/webp/1password.webp",
        src: "sponsors/gold/1password.png",
        url: "https://1password.com/",
        id: "gold_2",
      },
      {
        sponsorName: "Echo 3D",
        webp: "sponsors/gold/webp/echo3d.webp",
        src: "sponsors/gold/echo3d.png",
        url: "https://www.echo3d.co/",
        id: "gold_3",
      },
      {
        sponsorName: "GeeksForGeeks",
        webp: "sponsors/gold/webp/GFG.webp",
        src: "sponsors/gold/GFG.png",
        url: "https://www.geeksforgeeks.org/",
        id: "gold_4",
      },
      {
        sponsorName: "Interview Cake",
        webp: "sponsors/gold/webp/InterviewCake.webp",
        src: "sponsors/gold/InterviewCake.png",
        url: "https://www.interviewcake.com/",
        id: "gold_5",
      },
      {
        sponsorName: "Interview Buddy",
        webp: "sponsors/gold/webp/interviewbuddy.webp",
        src: "sponsors/gold/interviewbuddy.png",
        url: "https://polygon.technology/",
        id: "gold_6",
      },
      // {
      //   sponsorName: "Replit",
      //   webp: "sponsors/gold/webp/Replit.webp",
      //   src: "sponsors/gold/Replit.png",
      //   url: "https://replit.com/",
      //   id: "gold_7",
      // },
      {
        sponsorName: "Taskade",
        webp: "sponsors/gold/webp/Taskade.webp",
        src: "sponsors/gold/Taskade.png",
        url: "https://www.taskade.com/",
        id: "gold_8",
      },
      {
        sponsorName: "Badelog",
        webp: "sponsors/gold/webp/badelog.webp",
        src: "sponsors/gold/badelog.png",
        url: "https://www.badelog.in/",
        id: "gold_9",
      },
      {
        sponsorName: "Axure",
        webp: "sponsors/gold/webp/axure.webp",
        src: "sponsors/gold/axure.png",
        url: "https://www.axure.com/",
        id: "gold_10",
      },
      {
        sponsorName: "Cybrancee",
        webp: "sponsors/gold/webp/cybrancee.webp",
        src: "sponsors/gold/cybrancee.png",
        url: "https://www.cybrancee.com/",
        id: "gold_11",
      },
      {
        sponsorName: "Get Mega",
        webp: "sponsors/gold/webp/getmega.webp",
        src: "sponsors/gold/getmega.png",
        url: "https://www.getmega.com/",
        id: "gold_12",
      },
      {
        sponsorName: "Hack Club",
        webp: "sponsors/gold/webp/hackclub.webp",
        src: "sponsors/gold/hackclub.png",
        url: "https://www.hackclub.com/",
        id: "gold_13",
      },
      {
        sponsorName: "Hacks and Slacks",
        webp: "sponsors/gold/webp/hacksandslacks.webp",
        src: "sponsors/gold/hacksandslacks.png",
        url: "https://www.hacksslackshealthcare.com/",
        id: "gold_14",
      },
      {
        sponsorName: "Rosenfeld",
        webp: "sponsors/gold/webp/rosenfeld.webp",
        src: "sponsors/gold/rosenfeld.png",
        url: "https://rosenfeldmedia.com/",
        id: "gold_15",
      },
      {
        sponsorName: "Tech Cryptors",
        webp: "sponsors/gold/webp/techcryptors.webp",
        src: "sponsors/gold/techcryptors.png",
        url: "https://techcryptors.com/",
        id: "gold_16",
      },
      {
        sponsorName: "Packt",
        webp: "sponsors/gold/webp/packt.webp",
        src: "sponsors/gold/packt.png",
        url: "https://www.packtpub.com/",
        id: "gold_17",
      },
      {
        sponsorName: "Give My Certificate",
        webp: "sponsors/gold/webp/givemycertificate.webp",
        src: "sponsors/gold/givemycertificate.png",
        url: "https://givemycertificate.com/",
        id: "gold_18",
      },
      {
        sponsorName: "Clerky",
        webp: "sponsors/gold/webp/clerky.webp",
        src: "sponsors/gold/clerky.png",
        url: "https://clerky.com/",
        id: "gold_19",
      },
      {
        sponsorName: "Proto.io",
        webp: "sponsors/gold/webp/proto.webp",
        src: "sponsors/gold/proto.png",
        url: "https://proto.io/",
        id: "gold_20",
      },
      {
        sponsorName: "GrabOn",
        webp: "sponsors/gold/webp/grabon.webp",
        src: "sponsors/gold/grabon.jfif",
        url: "https://grabon.in/",
        id: "gold_21",
      },
      {
        sponsorName: "Voiceflow",
        webp: "sponsors/gold/webp/voiceflow.webp",
        src: "sponsors/gold/voiceflow.jfif",
        url: "https://grabon.in/",
        id: "gold_22",
      },
      {
        sponsorName: "Jetbrains",
        webp: "sponsors/gold/webp/jetbrains.webp",
        src: "sponsors/gold/jetbrains.jfif",
        url: "https://www.jetbrains.com/",
        id: "gold_23",
      },
      {
        sponsorName: "White Eagle",
        webp: "sponsors/gold/webp/white_eagle.webp",
        src: "sponsors/gold/white_eagle.jfif",
        url: "#",
        id: "gold_22",
      },
      {
        sponsorName: "Flipr",
        webp: "sponsors/bronze/webp/flipr.webp",
        src: "sponsors/bronze/flipr.jpg",
        url: "https://flipr.ai/",
        id: "gold_23",
      },
      {
        sponsorName: "Younity",
        webp: "sponsors/gold/webp/younity.webp",
        src: "sponsors/gold/younity.png",
        url: "https://younity.in/",
        id: "gold_24",
      },
      {
        sponsorName: "AoPS",
        webp: "sponsors/gold/webp/AoPS.webp",
        src: "sponsors/gold/AoPS.png",
        url: "https://artofproblemsolving.com/",
        id: "gold_25",
      },
      {
        sponsorName: ".xyz",
        webp: "sponsors/gold/webp/xyz.webp",
        src: "sponsors/gold/xyz.png",
        url: "https://gen.xyz/",
        id: "gold_26",
      },
    ],
    id: "2",
  },
  {
    tierName: "Community and Outreach Partners",
    data: [
      {
        sponsorName: "Youth Inc.",
        webp: "sponsors/bronze/webp/youth.webp",
        src: "sponsors/bronze/youth.jpg",
        url: "https://youthincmag.com/",
        id: "bronze_0",
      },
      {
        sponsorName: "Noticebard",
        webp: "sponsors/bronze/webp/noticebard.webp",
        src: "sponsors/bronze/noticebard.png",
        url: "https://www.noticebard.com/",
        id: "bronze_1",
      },
      {
        sponsorName: "Heiphen",
        webp: "sponsors/bronze/webp/heiphen.webp",
        src: "sponsors/bronze/heiphen.png",
        url: "https://heiphen.com/",
        id: "bronze_2",
      },
      {
        sponsorName: "Aglasem",
        webp: "sponsors/bronze/webp/aglasem.webp",
        src: "sponsors/bronze/aglasem.png",
        url: "https://aglasem.com/",
        id: "bronze_3",
      },
      {
        sponsorName: "Blog Adda",
        webp: "sponsors/bronze/webp/blogadda.webp",
        src: "sponsors/bronze/Blog Adda.png",
        url: "https://www.blogadda.com/",
        id: "bronze_4",
      },
      {
        sponsorName: "Pride TU",
        webp: "sponsors/bronze/webp/pride.webp",
        src: "sponsors/bronze/pride.png",
        url: "https://instagram.com/pride.tu?utm_medium=copy_link",
        id: "bronze_5",
      },
      {
        sponsorName: "MLSC KiiT",
        webp: "sponsors/bronze/webp/kiit.webp",
        src: "sponsors/bronze/kiit.jpg",
        url: "https://www.linkedin.com/company/msckiit/?originalSubdomain=in",
        id: "bronze_6",
      },
      {
        sponsorName: "Randomize",
        webp: "sponsors/bronze/webp/randomise.webp",
        src: "sponsors/bronze/randomise.jpg",
        url: "https://www.randomizemuj.com/",
        id: "bronze_7",
      },
      {
        sponsorName: "GirlUp",
        webp: "sponsors/bronze/webp/girlup.webp",
        src: "sponsors/bronze/girlup.jpg",
        url: "https://www.instagram.com/girluptiet",
        id: "bronze_8",
      },
      {
        sponsorName: "Code Dazzlers",
        webp: "sponsors/bronze/webp/code.webp",
        src: "sponsors/bronze/code.png",
        url: "https://www.codedazzlers.xyz/",
        id: "bronze_9",
      },
    ],
    id: "4",
  },
  {
    tierName: "Title Sponsors",
    data: [
      {
        sponsorName: "MLH",
        webp: "sponsors/title/webp/mlh.webp",
        src: "sponsors/title/mlh.png",
        url: "https://mlh.io/",
        id: "title_0",
      },
      {
        sponsorName: "Tech Analogy",
        webp: "sponsors/title/webp/techanalogy.webp",
        src: "sponsors/title/techanalogy.png",
        url: "https://techanalogy.org/",
        id: "title_1",
      },
      {
        sponsorName: "Devfolio",
        webp: "sponsors/title/webp/devfolio.webp",
        src: "sponsors/title/devfolio.png",
        url: "https://devfolio.co/",
        id: "title_2",
      },
      {
        sponsorName: "Polygon",
        webp: "sponsors/title/webp/polygon.webp",
        src: "sponsors/title/polygon.png",
        url: "https://polygon.technology/",
        id: "title_3",
      },
      {
        sponsorName: "Juspay",
        webp: "sponsors/title/webp/juspay.webp",
        src: "sponsors/title/juspay.png",
        url: "https://juspay.in/",
        id: "title_4",
      },
    ],
    id: "0",
  },


  // {
  //   tierName: "Our Partners",
  //   data: [
  //     {
  //       sponsorName: "GrabOn",
  //       webp: "sponsors/other/webp/grabon.webp",
  //       src: "sponsors/other/grabon.png",
  //       url: "https://www.grabon.in/",
  //       id: "title_2",
  //     },
  //     {
  //       sponsorName: "NoticeBard",
  //       webp: "sponsors/other/webp/noticebard.webp",
  //       src: "sponsors/other/noticebard.png",
  //       url: "https://www.noticebard.com/",
  //       id: "title_3",
  //     },
  //     {
  //       sponsorName: "StreamYard",
  //       webp: "sponsors/other/webp/streamyard.webp",
  //       src: "sponsors/other/streamyard.png",
  //       url: "https://streamyard.com/",
  //       id: "title_4",
  //     },
  //     {
  //       sponsorName: "LeadingLearners",
  //       webp: "sponsors/other/webp/leadinglearners.webp",
  //       src: "sponsors/other/leadinglearners.png",
  //       url: "http://linktr.ee/leadinglearners",
  //       id: "title_5",
  //     },
  //   ],
  //   id: "4",
  // },
];
